### ISSUE TITLE
requirements or pypi package

### ISSUE THREAD

**Issue by ogencoglu** [hasanjawad001/CGLearn#1]
Thanks for the work. Do you have a pip install pypi package? Or at least the requirements.txt and exact library versions?

**Comment by hasanjawad001** [comment]
Thank you for opening this issue! The `requirements.txt` file has been added to the repository, containing the bare minimum requirements needed to run the project. If further clarification is needed, feel free to reopen this issue or create a new one. Closing this now. 😊
